[package]
name = "rvision"
version = "0.1.0"
authors = ["Jhon James Quintero <jhon.quintero@alertlogic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
